DROP TABLE IF EXISTS professionals.public_projection_outbox_replays;
DROP TABLE IF EXISTS professionals.public_projection_outbox_cursors;
DROP TABLE IF EXISTS professionals.public_projection_outbox_deliveries;
DROP TABLE IF EXISTS professionals.public_projection_outbox_messages;
