DROP TABLE IF EXISTS administration_audit.public_projection_outbox_replays;
DROP TABLE IF EXISTS administration_audit.public_projection_outbox_cursors;
DROP TABLE IF EXISTS administration_audit.public_projection_outbox_deliveries;
DROP TABLE IF EXISTS administration_audit.public_projection_outbox_messages;
